// Email Service
// File: backend/services/emailService.js
// Handles sending emails with attachments

const { transporter } = require('../config/email');

/**
 * Send transaction report via email
 * 
 * @param {string} recipientEmail - Email to send to
 * @param {string} userName - User's name
 * @param {Buffer} pdfBuffer - PDF file as buffer
 * @returns {Promise<boolean>} true if email sent, false if disabled
 */
const sendTransactionReport = async (recipientEmail, userName, pdfBuffer) => {
  try {
    // Check if email is enabled
    if (!transporter) {
      console.log('⚠️ Email feature not enabled. Skipping email send.');
      return false;
    }

    // Prepare email
    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: recipientEmail,
      subject: `Finance Report - ${new Date().toLocaleDateString()}`,
      html: `
        <h2>Hello ${userName}!</h2>
        <p>Your finance report is attached.</p>
        <p><strong>What's in this report:</strong></p>
        <ul>
          <li>Summary of income and expenses</li>
          <li>Your current balance</li>
          <li>Detailed transaction history</li>
        </ul>
        <p>Keep track of your finances!</p>
        <hr>
        <p><em>Generated by Finance Management System</em></p>
      `,
      attachments: [
        {
          filename: `finance-report-${new Date().toISOString().split('T')[0]}.pdf`,
          content: pdfBuffer
        }
      ]
    };

    // Send email
    const info = await transporter.sendMail(mailOptions);
    console.log(`✅ Email sent to ${recipientEmail}. Message ID: ${info.messageId}`);
    return true;

  } catch (error) {
    console.error(`❌ Error sending email to ${recipientEmail}:`, error.message);
    return false;
  }
};

/**
 * Send simple notification email
 * 
 * @param {string} recipientEmail - Email to send to
 * @param {string} subject - Email subject
 * @param {string} message - Email message
 * @returns {Promise<boolean>} true if sent, false otherwise
 */
const sendEmail = async (recipientEmail, subject, message) => {
  try {
    if (!transporter) {
      console.log('⚠️ Email feature not enabled.');
      return false;
    }

    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: recipientEmail,
      subject: subject,
      html: message
    };

    const info = await transporter.sendMail(mailOptions);
    console.log(`✅ Email sent to ${recipientEmail}`);
    return true;

  } catch (error) {
    console.error(`❌ Error sending email:`, error.message);
    return false;
  }
};

/**
 * Send overspending notification email
 * Called when user exceeds their monthly budget
 * 
 * @param {string} recipientEmail - User's email
 * @param {string} userName - User's name
 * @param {number} budget - Monthly budget limit
 * @param {number} currentSpending - Current spending amount
 * @returns {Promise<boolean>} true if sent, false otherwise
 */
const sendOverspendingAlert = async (recipientEmail, userName, budget, currentSpending) => {
  try {
    if (!transporter) {
      console.log('⚠️ Email feature not enabled. Skipping overspending alert.');
      return false;
    }

    // Calculate how much over budget
    const overspendAmount = currentSpending - budget;
    const percentageOver = ((overspendAmount / budget) * 100).toFixed(1);

    // Create email message
    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: recipientEmail,
      subject: '⚠️ Budget Alert: You are Overspending!',
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #dc2626;">⚠️ Budget Alert</h2>
          
          <p>Hello <strong>${userName}</strong>,</p>
          
          <p>We noticed that your spending has exceeded your monthly budget.</p>
          
          <div style="background-color: #fee2e2; border-left: 4px solid #dc2626; padding: 15px; margin: 20px 0;">
            <p><strong>Your Budget Status:</strong></p>
            <ul style="list-style: none; padding: 0;">
              <li>📊 Monthly Budget: <strong>₹${budget.toFixed(2)}</strong></li>
              <li>💸 Current Spending: <strong>₹${currentSpending.toFixed(2)}</strong></li>
              <li>⚠️ Over Budget: <strong>₹${overspendAmount.toFixed(2)} (${percentageOver}%)</strong></li>
            </ul>
          </div>
          
          <h3>💡 Tips to Reduce Spending:</h3>
          <ul>
            <li>Review your recent transactions and identify unnecessary expenses</li>
            <li>Cut back on discretionary spending (entertainment, dining out, etc.)</li>
            <li>Look for subscription services you can cancel</li>
            <li>Plan your meals to reduce food expenses</li>
            <li>Set daily spending limits for the rest of the month</li>
          </ul>
          
          <p style="color: #666; font-size: 14px; margin-top: 30px;">
            <em>This is an automated alert from your Finance Management System. 
            Please review your spending and adjust your budget accordingly.</em>
          </p>
          
          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
          <p style="color: #999; font-size: 12px;">
            Finance Management System | Helping you manage your money better
          </p>
        </div>
      `
    };

    // Send email
    const info = await transporter.sendMail(mailOptions);
    console.log(`✅ Overspending alert sent to ${recipientEmail}`);
    return true;

  } catch (error) {
    console.error(`❌ Error sending overspending alert:`, error.message);
    return false;
  }
};

module.exports = { sendTransactionReport, sendEmail, sendOverspendingAlert };
